@baseUrl = http://localhost:3000/api

# Products

### get products
GET {{baseUrl}}/products


### add new acategory
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Iphone X"
}


### update a products
PATCH {{baseUrl}}/products/2
Content-Type: application/json

{
  "name": "Iphone XI"
}

### filter

GET {{baseUrl}}/products?color=yellow

### filter have text
GET {{baseUrl}}/products?name_like=Slee


### pagination
GET {{baseUrl}}/products?_page=1&_limit=1

### sort
GET {{baseUrl}}/products?_sort=price&_order=asc
